# ----
# Site

title: apiato
url: "https://github.com/apiato/apiato"
baseurl:
google_analytics_key: UA-37514928-7
show_full_navigation: true

# Values for the jekyll-seo-tag gem (https://github.com/jekyll/jekyll-seo-tag)
logo: /images/apiato.jpg
description: APIATO, a flawless framework for building scalable and testable API-Centric Apps with PHP and Laravel.
author:
  name: Mahmoud Zalt
  email: mahmoud@zalt.me
  twitter: Mahmoud_Zalt
social:
  name: APIATO
  links:
    - http://apiato.io
twitter:
  username: Mahmoud_Zalt
# -----
# Build

permalink: pretty

gems:
  - jekyll-sitemap
  - jekyll-seo-tag
  - jekyll-feed

exclude:
  - Gemfile
  - Gemfile.lock

collections:
  docs:
    title: Documentation
    permalink: /:path/
    output: true

defaults:
  -
    scope:
      path: ""
    values:
      layout: default
  -
    scope:
      path: ""
      type: "docs"
    values:
      seo:
        type: Documentation
      _comments:
        category: Group navigation links with this field
        order: Used to sort links in the navigation
  -
    scope:
      path: ""
      type: "posts"
    values:
      _comments:
        type: Marks the impact of this release

categories-order:
 - Getting Started
 - Features
 - Main Components
 - Optional Components
 - Miscellaneous

# -----------
# CloudCannon

types:
  - minor
  - major
